version: '3.8'

services:
  # React App Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: always
    networks:
      - react-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - react_build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - react-network

  # PostgreSQL Database Service
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reactdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    networks:
      - react-network

# Volumes for persistent storage
volumes:
  react_build:
  postgres_data:

# Networks for isolated communication
networks:
  react-network:
